### ISSUE TITLE
Differences between *this and original implementation

### ISSUE THREAD

**Issue by Kedryn** [davidrapan/ha-solarman#14]
i switched from the original repo to yours, trying to fix a problem with 2 of my inverters, but i noticed that:
- status_connection property is named connection_status in your build. Is that intended?
- status_lastupdate is missing

it would be nice to have same basic properties, or not?

**Comment by davidrapan** [comment]
Hi, thank you for your post and questions!

When comes to changes like this... I preserved things from the original integration which makes sense and changed those which did not. In your particular example first point is about grammar and friendly name (the one without underscore). And the second point is because I'm using HAs "features" to accomplish same thing. Meaning there is no need for separate sensor for that. And not even taking in the consideration that that sensor brings 0 value.

The second perspective is that those sensor even exists just because the solarman protocol in the implementation of original integration was very, very, very unstable and you really needed to know what is happening in terms of diagnostics, etc. When you for example look at other components/integration of HA (built-in ones and also third-party) they don't really have sensors which says connection states and so on cause it makes no sense when integration does what it should and does it correctly.

That being said I left the sensor which tracks connection state there, and improved it to also include information about last update. If you want to really track statistics of how long it takes, in average, for integration to update, Look at Diagnostics section the readme of this repo. It will provide additional sensors which gives you far more information than original integration ever was.

If you have any more questions feel free to ask!

Have fun!
