### ISSUE TITLE
deye_hybrid battery state is always "charging"

### ISSUE THREAD

**Issue by voed** [davidrapan/ha-solarman#151]
![image](https://github.com/user-attachments/assets/50b5ae9a-2374-4601-a9ba-16cfc9534064)
Hi. I have a Deye SUN-6KSG05LP1-EU inverter and the battery state does not change. Are there any way to fix that?

**Comment by davidrapan** [comment]
Hi @voed, I can see in the inverter profile that the sensor is register based so it does read the value from your inverter. But it can be wrong though... I'm not the author of said inverter profile nor do I have documentation for your device to be able to determine the root cause of your issue... :-/
