### ISSUE TITLE
Deye inverter on parallel

### ISSUE THREAD

**Issue by bmatti996** [davidrapan/ha-solarman#189]
hi i have 2 deye inverter 6kw with the solarman stick logger and the integration see only the master 

![Immagine 2024-10-02 231700](https://github.com/user-attachments/assets/16ef6f3b-a8ec-40f4-9a1d-ef9880894720)
[home-assistant_solarman_2024-10-02T21-12-00.412Z.log](https://github.com/user-attachments/files/17236119/home-assistant_solarman_2024-10-02T21-12-00.412Z.log)

**Comment by davidrapan** [comment]
Hi @bmatti996 It looks like you're using wrong serial number.

You are using correct serial number for 192.168.178.192 which is 2907XXXXXX but for 192.168.178.52 you set 2312XXXXXX which is not correct (probably serial number of the inverter instead of the stick logger) and you should use serial number which starts like this 2905XXXXXX.

😉

**Comment by bmatti996** [comment]
thanks you,
now it works
